apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f Compose/docker-compose.yaml --volumes configMap
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: pingfederate
  name: pingfederate
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pingfederate
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f Compose/docker-compose.yaml --volumes configMap
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: pingfederate
    spec:
      containers:
      - args:
        - wait-for
        - pingdirectory:389
        - -t
        - "600"
        - --
        - entrypoint.sh
        - start-server
        env:
        - name: HTTPS_PORT
          valueFrom:
            configMapKeyRef:
              key: HTTPS_PORT
              name: env-vars
        - name: PF_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: PF_LOG_LEVEL
              name: env-vars
        - name: PF_USER_PWD
          valueFrom:
            configMapKeyRef:
              key: PF_USER_PWD
              name: env-vars
        - name: PING_IDENTITY_ACCEPT_EULA
          valueFrom:
            configMapKeyRef:
              key: PING_IDENTITY_ACCEPT_EULA
              name: env-vars
        - name: REST_API_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: REST_API_HOSTNAME
              name: env-vars
        - name: SERVER_PROFILE_PATH
          value: pingfederate
        - name: SERVER_PROFILE_URL
          value: https://github.com/pingidentity/Customer360.git
        - name: USER_BASE_DN
          valueFrom:
            configMapKeyRef:
              key: USER_BASE_DN
              name: env-vars
        image: pingidentity/pingfederate:latest
        imagePullPolicy: ""
        name: pingfederate
        ports:
        - containerPort: 9031
        - containerPort: 9999
        resources: {}
        envFrom:
          - secretRef:
              name: devops-secret
      restartPolicy: Always
      serviceAccountName: ""
status: {}
