server:
  rootPath: "/api/"
  registerDefaultExceptionMappers: false
  adminConnectors: []
  applicationConnectors:
  - type: "https"
    port: "${PING_PORT:-443}"
    keyStoreType: "${PING_KEYSTORE_TYPE:-PKCS12}"
    keyStorePath: "${PING_KEYSTORE_PATH:-config/keystore.p12}"
    keyStorePassword: "${PING_KEYSTORE_PASSWORD:-75351098}"
    certAlias: "${PING_CERT_ALIAS:-server-cert}"
    validateCerts: "false"
    validatePeers: "false"
core:
  Database.Type: "H2"
  Database.H2.Mode: "file"
  Database.ConnectionString: "jdbc:h2:file:./Symphonic"
  Database.User: "pap_user"
  Database.Password: "Symphonic2014!"
  Authentication.DecisionPoint.Protocol: "shared secret"
  Authentication.SharedSecret: "${PING_SHARED_SECRET:-2FederateM0re}"
  License.Path: "PingDataGovernance.lic"
  DecisionResponse.AuditLogView: "Errors,Statements,EncryptSecrets,EvaluationLog,Request"
enableUIServing: true
enableSwagger: true
ui:
  REST_URL: "https://${PING_HOSTNAME:-pingdatagov-pap-ping-cloud-devops-eks-cprice.ping-devops.com}/api/"
  statements:
  - "config/advice/add-filter.json"
  - "config/advice/combine-scim-search-authorizations.json"
  - "config/advice/custom-advice.json"
  - "config/advice/denied-reason.json"
  - "config/advice/exclude-attributes.json"
  - "config/advice/filter-response.json"
  - "config/advice/include-attributes.json"
  - "config/advice/modify-attributes.json"
  - "config/advice/modify-query.json"
  authType: "credentials"
  usernames: "${PING_USERNAMES:-admin}"
logging:
  level: "INFO"
  loggers:
    DataNucleus: "ERROR"
    DataNucleus.Enhancer: "OFF"
    org.glassfish.jersey.internal.Errors: "ERROR"
    com.symphonicsoft.policyanalysis.PolicyTranslator: "ERROR"
    DECISION_AUDIT_LOG:
      level: "INFO"
      additive: false
      appenders:
      - type: "file"
        currentLogFilename: "logs/decision-audit.log"
        archive: true
        maxFileSize: "250MB"
        archivedLogFilenamePattern: "logs/decision-audit.%i.log.gz"
        archivedFileCount: 10
        logFormat: "[%date{ISO8601}] %msg%n"
    DECISION_DIAGNOSTIC_LOG:
      level: "OFF"
      additive: false
      appenders:
      - type: "file"
        currentLogFilename: "logs/decision-diagnostic.log"
        archive: true
        maxFileSize: "250MB"
        archivedLogFilenamePattern: "logs/decision-audit.%i.log.gz"
        archivedFileCount: 10
        logFormat: "%msg%n"
    MANAGEMENT_AUDIT:
      level: "INFO"
      additive: false
      appenders:
      - type: "file"
        currentLogFilename: "logs/management-audit.log"
        archive: false
        archivedLogFilenamePattern: "logs/management-audit.%i.log.gz"
        archivedFileCount: 10
        logFormat: "[%date{ISO8601}] %msg%n"
    metrics:
      additive: false
      appenders:
      - type: "file"
        currentLogFilename: "logs/metrics.log"
        maxFileSize: "250MB"
        archive: true
        archivedLogFilenamePattern: "logs/metrics.%i.log.gz"
        archivedFileCount: 10
        logFormat: "logger=metrics, timestamp=%date{yyyyMMdd'T'HHmmss.SSS}, %msg%n"
  appenders:
  - type: "console"
    threshold: "INFO"
    target: "stdout"
    logFormat: "%-5level [%date{ISO8601}] %c: %msg%n"
  - type: "file"
    currentLogFilename: "logs/debug.log"
    maxFileSize: "250MB"
    archive: true
    archivedLogFilenamePattern: "logs/debug.%i.log.gz"
    archivedFileCount: 10
    logFormat: "%-5level [%date{ISO8601}] [%thread] %c: %msg%n"